services:
  diablo2:
    container_name: diablo2-server
    build: .
    image: diablo2-full:1.0
    network_mode: host
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/start.sh"]
    volumes:
      - ./logs/bnetd.log:/pvpgn/var/pvpgn/bnetd.log
      - ./logs/d2gs.log:/root/.wine/drive_c/d2gs/d2gs.log
      - ./logs/d2ge.log:/root/.wine/drive_c/d2gs/d2ge.log
